openSUSE/libzypp

- tests/zypp/CpeId_test.cc
If 'char' is unsigned by default (e.g. on s390\*, ppc\*, arm\*), then the loop will run forever (since 'ch' will always be greater or equal than zero, even after overflow).
Make sure to increase until the actual maximum value for char.
> fix CpeId_test on archs where char is unsigned

- zypp/VendorAttr.cc
When adding a new directory with vendor configuration, do not try to read the directory as if it was a config/ini file, which is going to always fail (and whose result was discarded anyway).
> VendorAttr: do not try to read a directory as file

- zypp/KeyRing.cc
- zypp/PublicKey.cc
On systems where `gpg` is not available, checking the public key
would fail. Use `GPG_BINARY` in both `PublicKey.cc` and `KeyRing.cc`,
and define it in a single place only (`ExternalProgram.h`).
> zypp/PublicKey.cc: Use GPG_BINARY from KeyRing.cc

- zypp.conf
- zypp/ZConfig.cc
- zypp/ZConfig.h
- zypp/solver/detail/SystemCheck.cc
- zypp/solver/detail/SystemCheck.h
Reads files from `/etc/zypp/systemCheck.d` (default) in alphabetical order and adds the listed requires and conflicts rules to the system requirements as if they would be listed in the file `/etc/zypp/systemCheck`.
We use this downstream in Nemo Mobile / Sailfish OS to be able to ship custom additions to the `systemCheck` file easily.
> Support for *.check files in the systemCheck.d directory

- zypp/ZConfig.cc
we want rebuilds to be identical
and embedding build time prevents that.
> fix build-compare

- libzypp.spec.cmake
By using pkgconfig(libudev) OBS prefers libudev-mini-devel which may
allow libzypp to start building earlier in a full rebuild. The full udev
package is behind texlive so takes hours.
> Avoid direct BuildRequire on libudev-devel

- zypp/misc/CheckAccessDeleted.cc
fixes https://bugzilla.opensuse.org/show_bug.cgi?id=980541
> use more user friendly command names for "zypper ps"

- zypp/repo/SUSEMediaVerifier.cc
isDesiredMedia() media may fail, which ultimately causes a
MediaNotDesiredException to be thrown. To ease debugging, print the
values of the (cached) media id and vendor in zypper's log when running
with ZYPP_FULLLOG=1.
Also remove the superfluous CPP warning. ifstream.getline() throws an
exception in case something goes wrong while reading the file.
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
**An example log can be seen below. Having had this information could have saved some time while debugging https://github.com/openSUSE/docker-containers/issues/57:**
2017-07-01 13:55:34 <1> 4fa6b2226328(22) [zypp++] SUSEMediaVerifier.cc(isDesiredMedia):60 reading data from repository media: /var/tmp/AP_0xGuawE5/media.1/media
2017-07-01 13:55:34 <1> 4fa6b2226328(22) [zypp++] …
> SUSEMediaVerifier: add debug logs

- zypp/PathInfo.cc
- zypp/PathInfo.h
The `rename(2)` systemcall doesn't succeed across devices, which is likely
to happen when using the overlay storage driver in Docker when trying to
rename between the upper and the lower layer. In such case, errno is
set to *EXDEV*.
Extend `PathInfo::rename` to handle the *EXDEV* errno case and fallback to
using `mv(1)`, which is explicitly mentioned in the kernel docs to deal
correctly with OverlayFS issues.
**Fixes:** https://github.com/openSUSE/docker-containers/issues/57
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
> rename: handle EXDEV error on OverlayFS

- zypp/base/ReferenceCounted.cc
By default, destructors are noexcept as per c++-11 standards. So compiler will warn about thorw statement.
> Fix c++-11 compiler warning

- libzypp.spec.cmake
Historically, the test suite for libzypp hasn't been run in package builds, which leads to issues where problems with the test suite aren't caught when things like rpm and libsolv are upgraded.
By enabling them all the time, this should prevent these kinds of failures from slipping through.
> Enable tests for libzypp package builds

- zypp/KeyManager.cc
For easier debugging of libgpgme problems it will help us to list the loaded gpgme library version in the log file.
> Show GPGME version in log

- zypp/misc/CheckAccessDeleted.cc
This patch makes zypper ignore additional directories that are not relevant for "zypper ps". Since we only want to detect files that are removed by package changes/removals we don't need to care about directories where packages usually do not own files.
> Ignore /var, /tmp and /proc in zypper ps (bsc#1096617)

- zypp/Fetcher.cc
- zypp/MediaSetAccess.h
- zypp/PathInfo.h
Rewrote Fetcher to move only validated files to the final destination.  A file already found at the final destination, but not validating, will be unlinked.
This behavior is desired to fix [bsc#1091624](https://bugzilla.suse.com/show_bug.cgi?id=1091624). Package signature check will be moved to the Fetcher, so we don't get unchecked Packages into the cache.
> Ma fix fetcher checks

- zypp/ZConfig.cc
- zypp/ZConfig.h
This patch adds setter functions to support the fix for openSUSE/zypper#180
> Add setter functions for zypp cache related config values to ZConfig

- zypp/KeyManager.cc
- no error reporting, no tmpfile when only retrieving the fingerprints
- restore the old (GPG2) behavior: accept valid sig even if the key is meanwhile expired
> Ma adjust sigchecks

- zypp/FileChecker.h
- zypp/ProvideFilePolicy.h
- zypp/repo/PackageProvider.cc
- zypp/repo/RepoProvideFile.cc
Fixing [bsc#1091624](https://bugzilla.suse.com/show_bug.cgi?id=1091624)
The packages sig check code was moved into a FileChecker passed down to the Fetcher. This avoids the package being moved into the cache before the check has completed.
> Ma fix pkgsigcheck

- zypp/CMakeLists.txt
- zypp/ExternalProgram.cc
- zypp/ExternalProgram.h
- zypp/ShutdownLock.cc
- zypp/ShutdownLock_p.h
- zypp/target/TargetImpl.cc
(fixes openSUSE/zypper#135)
This patch prevents the system from shutting down or hibernating when a zypper commit is running.
> Prevent the system from sleeping during a commit

- tests/lib/WebServer.cc
As of Boost 1.68.0, the System library headers were updated
which breaks the hack for inlining some functions in
older Boost versions. Use proper define starting with this
Boost version before including Boost.System headers.
This only seems to affect one test.
> Fix build with Boost 1.68.0

- zypp/KeyRing.cc
- zypp/KeyRing.h
- zypp/PublicKey.cc
- zypp/target/rpm/RpmDb.cc
After importing multiple keys from rpmdb check if all of them were expected. If not show it in the logs.
> Check for not imported keys after multi key import from rpmdb

- tests/lib/TestSetup.h
- zypp/KeyRing.cc
- zypp/KeyRing.h
- zypp/RepoInfo.cc
- zypp/RepoInfo.h
- zypp/repo/PackageProvider.cc
This patch makes sure libzypp will download signing keys from gpgkey entries to check repository signatures. Before it would only do that for package signatures.
> Automatically fetch repository signing key from gpgkey url (bsc#1088037)

- tests/zypp/CMakeLists.txt
- tests/zypp/PoolQueryCC_test.cc
- tests/zypp/PoolQuery_test.cc
- tests/zypp/StrMatcher_test.cc
- tests/zypp/base/String_test.cc
- tests/zypp/data/PoolQuery/savedqueries
- tests/zypp/data/PoolQueryCC/rxnames.xml
- zypp/Locks.cc
- zypp/Pathname.cc
- zypp/PoolQuery.cc
- zypp/PoolQuery.h
- zypp/Product.cc
- zypp/base/String.cc
- zypp/base/String.h
- zypp/media/MediaPlugin.cc
- zypp/media/MediaPlugin.h
- zypp/solver/detail/Testcase.cc
The initial commits are more or less cleanups. Most important are last 2, correctly escaping STRING and GLOB when compiled into a single REGEX.
Fixes [(bsc#1099982)](https://bugzilla.suse.com/show_bug.cgi?id=1099982).
> Ma 1099982 searchrx

- zypp/sat/Pool.cc
- zypp/sat/Pool.h
- zypp/sat/Solvable.cc
- zypp/sat/Solvable.h
- zypp/sat/SolvableType.h
- zypp/sat/detail/PoolImpl.h
- zypp/target/TargetImpl.cc
This patch adds the infrastructure to provide a "zypper reboot-needed" type of command. It introduces a new set of config files in /var/lib/zypp that can be used to tweak the behaviour.
> Add infrastructure to flag specific packages to trigger a reboot needed hint (fate#326451)

- zypp/TriBool.h
operator== between boost::logic::tribool returns a tribool, which
requires an explicit cast to bool
This results in a build failure with upcoming Boost 1.69.0
https://build.opensuse.org/package/live_build_log/home:adamm:boost_test/libzypp/openSUSE_Tumbleweed/x86_64
```
[   64s] In file included from /home/abuild/rpmbuild/BUILD/libzypp-17.9.0/zypp/ZConfig.h:27,
[   64s]                  from /home/abuild/rpmbuild/BUILD/libzypp-17.9.0/zypp/ZYpp.h:21,
[   64s]                  from /home/abuild/rpmbuild/BUILD/libzypp-17.9.0/zypp/ZYppFactory.h:18,
[   64s]                  from /home/abuild/rpmbuild/BUILD/libzypp-17.9.0/zypp/misc/DefaultLoadSystem.cc:19:
[   64s] /home/abuild/rpmbuild/BUILD/libzypp-17.9.0/zypp/TriBool.h: In function 'bool boost::logic::sameTriboolState(boost::logic::tribool, …
```
> Boost.Tribool requires an explicit cast to bool

- zypp/RepoInfo.cc
- zypp/RepoManager.cc
- zypp/repo/Applydeltarpm.cc
Only explicit casts are allowed as of Boost 1.69
These are additional changes required for Tumbleweed with Boost 1.69.
https://github.com/openSUSE/libzypp/commit/867c6b3190dafcd07f0ac5d8eef39268cc925141 was incomplete.
> Need to explitily cast of Tribool to boolean

- libzypp.spec.cmake
- tests/data/TCNamespaceRecommends/solver-system.xml
- tests/data/TCNamespaceRecommends/solver-test.xml
- tests/data/TCNamespaceRecommends/update.xml
- tests/zypp/CMakeLists.txt
- tests/zypp/Resolver_test.cc
- zypp.conf
- zypp/Resolver.cc
- zypp/Resolver.h
- zypp/solver/detail/Resolver.cc
- zypp/solver/detail/Resolver.h
- zypp/solver/detail/SATResolver.cc
- zypp/solver/detail/SATResolver.h
- zypp/solver/detail/Testcase.cc
In the 1st iteration we unconditionally resolve namespaces, even if `no-recommends` is on.  Technically those namespaces (hardware,language,filesystem support) are recommends, but in fact they are more important than ordinary recommends.
Questionable whether there are usecases which actually require turning off the namespaces as well. If so, we can still offer additional switches...
> Ma fate#325513 resolver namespaces

- zypp/PoolItemBest.cc
- zypp/PoolItemBest.h
Add ctor argument to prefer not locked packages. This helps to differ between the *best available* and *best installable* version. 
Zypper does a poor job when handling partially locked items, as it always heads for the *best available* item, even if this version is locked. This is causing unnecessary conflicts ([bsc#1113296](https://bugzilla.suse.com/show_bug.cgi?id=1113296)).
> PoolItemBest: Optionally prefer not locked packages (bsc#1113296)

- tests/zypp/Url_test.cc
- zypp/Url.cc
- zypp/repo/RepoVariables.cc
Some Url schemata per default suppressed printing an *empty authority*, as they do not allow defining an authority at all (mailto,plugin,...). The patch uses this default for more schemata without authority (dir, cd, iso,...). This changes their default string representation from e.g. `dir:///path` to `dir:/path`.
The RepoVariablesUrlReplacer accidentally amended the Urls default viewoption. The patch makes sure the returned Url has the same viewoptions as the original one. By now more a cosmetical issue if `plugin:foo` is suddenly printed as `plugin:/foo`, but the replacer should just substitute variables, nothing else.
> Ma unwanted url rewrite

- zypp/sat/detail/PoolImpl.cc
YAST seems to pass an empty locale if `LANG=''`. In this case `fallbacklist_cstr.front` crashes as the vector is empty. So we set `en` as last resort.
> Prevent SEGV if the application sets an empty TextLocale

- zypp/KeyManager.cc
- zypp/target/rpm/RpmDb.cc
Work around [[libgpgme] gpgme_op_import issue when signal is received (e.g. CTRL-C in zypper)](https://bugzilla.suse.com/show_bug.cgi?id=1127220). Silently not imported keys are otherwise reported as _probably unsupported gpg V3 keys_.
> Ma wrong gpgv3 key error on ctrl c

- .clang-format
- zypp/ResolverProblem.cc
- zypp/ResolverProblem.h
- zypp/solver/detail/SATResolver.cc
- zypp/solver/detail/SATResolver.h
Libsolv offers more information about problems than we currently show
to the user. This patch enables libzypp to get the full set of
information. Also it removes some duplicate code from libzypp that is
already present in libsolv.
> Provide more information about problems

- libzypp.spec.cmake
- package/libzypp.changes
Starting with CMake 3.14, EXCLUDE_FROM_ALL now spreads from
directories to targets. 'make -C someSubdir' when 'someSubdir'
uses the 'EXCLUDE_FROM_ALL' keyword does nothing.
Fixes #365
> Fix the openSUSE package when using CMake >= 3.14

- zypp/target/RpmPostTransCollector.cc
When running a posttrans script, according to https://en.opensuse.org/openSUSE:Packaging_scriptlet_snippets (and fedora's equivilant https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/ ) a posttrans script should be given the value '0' as a parameter. Right now libzypp gives no arguments.
Original issue was found when installing gitlab-ce. Its posttrans script is located at https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/config/templates/package-scripts/posttrans.erb (the important part is the bottom `case`). Roughly it checks if $1 is 0 (identifying it as rpm, though this script only runs for rpm anyways) and then runs its script. Since libzypp doesnt pass this on, it never triggers.
A test rpm can be found at …
> Give posttrans script a parameter of 0

- zypp/KeyManager.cc
- zypp/KeyManager.h
- zypp/KeyRing.cc
- zypp/PublicKey.cc
- zypp/RepoManager.cc
Preparing the context and setting up the keyring must succeed, otherwise the calling methods are lost. `createForOpenPGP` was changed to prepare context and keyring in one go and to throw a `KeyRingException` on error.
Also dropped the outer `shared_ptr<KeyManagerCtx>` and let `createForOpenPGP` return the `KeyManagerCtx` directly.
The `KeyManager.cc` diff looks more complicated than the change actually is: 
- `Impl` stores the gpgme context, so it is now also responsible for releasing it.
- `createForOpenPGP` was changed to return a `KeyManagerCtx`, throw on error and immediately sets the homedir/keyring.
- `setHomedir()` was dropped.
- `listKeys()` temporarily sets `GPGME_KEYLIST_MODE_SIGS`.
- `readKeyFromFile()`  works around bsc#1140670 by using a temp. keyring if necessary (a version …
> KeyManagerCtx: rewrite API to take the keyring when constructing the context

- zypp/AutoDispose.h
- zypp/media/MediaCurl.cc
- zypp/media/MediaMultiCurl.cc
To test run eg. `watch ls -l /proc/\$\(cat /var/run/zypp.pid\)/fd` in a root shell to monitor the file descriptors in use. Then in an other window `rm -r /var/cache/zypp/raw/; zypper dup --dry-run --force-resolution` until the summary appears.
The PR so far fixes the open FDs to `/dev/null` from the curl backend, but it looks like the multicurl backend misses to close some sockets. Will look after it.
> bsc#1116995 leaking fds in curl backends

- zypp/MediaSetAccess.cc
It's a pity that MediaAccessId is an unsigned and not some shared_ptr.
Releasing the media on destruction is not enough. The MediaAccess handle
stays in the MediaManagers mediaMap waiting forever to be re-attached. The
map grows and is populated with dead handles, if the media is not closed
before the last MediaAccessId vanishes.
This also closes all the the open sockets we saw in https://github.com/openSUSE/libzypp/pull/179.
> MediaSetAccess: Close media handles on destruction

- zypp/media/MediaMultiCurl.h
[(bsc#1153557)](https://bugzilla.suse.com/show_bug.cgi?id=1153557)
> Fix empty metalink downloads if filesize is unknown (bsc#1153557)

- libzypp.spec.cmake
- zypp/sat/Pool.cc
- zypp/sat/Pool.h
- zypp/sat/Solvable.cc
- zypp/sat/Solvable.h
Extend zypp::sat::Pool by wrapping the pool_whatmatchesdep
functionality from libsolv. This is required to implement a reverse dependency search
in zypper (fixes openSUSE/zypper#214)
> Expose pool_whatmatchesdep from zypp::sat::Pool

- libzypp.spec.cmake
- zypp/sat/detail/PoolImpl.cc
- zypp/solver/detail/SATResolver.cc
Unrelated but included: Add solver jobs for retracted packages and ptfs which are provided by libsolv-devel >= 0.7.8.
> Do not enforce 'en' being in RequestedLocales (bsc#1155678)

- tests/lib/TestSetup.h
- zypp/solver/detail/SATResolver.cc
[bsc#1155819](https://bugzilla.suse.com/1155819)
On distupgrade let the solver determine the new products to install, then in a 2nd run clean the packages the products dropped.
> Ma 1155819   weakremovers of future product not evaluated

- zypp/ui/Selectable.cc
- zypp/ui/Selectable.h
- zypp/ui/SelectableImpl.h
- zypp/ui/SelectableTraits.h
Sorted to the end of the available items list. They are still
considered if explicitly selected or nothing else is available.
> Selectable: avoid using retracted items as candidate (jira#SLE-8905)

- tests/parser/HistoryLogReader_test.dat
- zypp/HistoryLog.cc
- zypp/HistoryLog.h
- zypp/HistoryLogData.cc
- zypp/PoolItem.cc
- zypp/PoolItem.h
- zypp/ResPool.cc
- zypp/ResPool.h
- zypp/ResStatus.cc
- zypp/ResStatus.h
- zypp/pool/PoolImpl.cc
- zypp/pool/PoolImpl.h
- zypp/sat/Transaction.h
- zypp/solver/detail/SATResolver.cc
- zypp/target/TargetImpl.cc
[SLE-5116](https://jira.suse.com/browse/SLE-5116)
Basically ResPool stores the computed patch status whenever the pool content changes (repo add/remove). Upon commit patches were the status is changed by the commit are remembered in the history.
Adapted the history type for patch status changes a bit.
Ready for review, just the last commit (https://github.com/openSUSE/libzypp/commit/932874f4ead400f5e335822a1d1978a25b6799a3) will need to be tuned in case the commit is aborted. In this case some patches may not have completed their status change. Need to figure out which and omit them in the history.
> SLE-5116 log patch status changes in history

- zypp/parser/HistoryLogReader.cc
- zypp/parser/HistoryLogReader.h
A small fix in the 1st commit. The action filter discards unwanted action types already inside the parser.
> Add history log reader action filter

- tests/zypp/PurgeKernels_test.cc
- tests/zypp/data/PurgeKernels/simple/solver-system.xml
- zypp/PurgeKernels.cc
This patch changes current behaviour to keep devel/source packages around if no corresponding kernel for them were removed in the first step to avoid building up a list of installed but orphaned devel/source packages. This happens due to package rebuilds that do not obsolete the previous release: kernel-source-1-1.1 vs kernel-source-1-1.2
> Fix bsc#1171224: Older kernel-devel packages are not properly purged.

- tests/repo/yum/YUMDownloader_test.cc
- zypp/repo/yum/Downloader.cc
This patch enables basic zchunk download support if the corresponding libsolv feature is enabled.
Basic support does not include optimized zchunk download but instead always downloads the full file.
> Enable basic zchunk download if libsolv supports it

- doc/autoinclude/EnvironmentVariables.doc
- zypp/ZYppCallbacks.h
- zypp/target/TargetCallbackReceiver.cc
- zypp/target/TargetCallbackReceiver.h
- zypp/target/rpm/RpmDb.cc
`ZYPP_RPM_DEBUG` environment variable to log verbose rpm output. Additionally offer output lines immediately via custom callback.
> Write rpm -vv output into the log

- .clang-format
- tests/zyppng/media/EvDownloader_test.cc
- zypp/media/MediaCurl.cc
- zypp/media/MediaUserAuth.cc
- zypp/media/MediaUserAuth.h
- zypp/zyppng/media/network/downloader.cc
This patch changes the default behaviour of libzypp handling authentication. 
Currently we would first try without authentication and wait for a server response with auth failed. 
The new behaviour proactively sends credentials if the URL specifes ?auth=basic and a username in the URL.
> Fix bsc 1174011

- zypp/parser/xml/libxmlfwd.h
Trying to build libzypp on Arch fails with:
```
In file included from /usr/include/c++/10.1.0/bits/unique_ptr.h:37,
from /usr/include/c++/10.1.0/memory:83,
from /usr/include/unicode/localpointer.h:45,
from /usr/include/unicode/uenum.h:23,
from /usr/include/unicode/ucnv.h:53,
from /usr/include/libxml2/libxml/encoding.h:31,
from /usr/include/libxml2/libxml/parser.h:810,
from /usr/include/libxml2/libxml/globals.h:18,
from /usr/include/libxml2/libxml/threads.h:35,
from /usr/include/libxml2/libxml/xmlmemory.h:218,
from /usr/include/libxml2/libxml/tree.h:1307,
from /usr/include/libxml2/libxml/xmlreader.h:14,
from /home/daan/projects/libzypp/src/libzypp-17.24.1/zypp/parser/xml/libxmlfwd.h:17,
from /home/daan/projects/libzypp/src/libzypp-17.24.1/zypp/parser/xml/libxmlfwd.cc:15: …
```
> Fix template with C linkage build error

- po/it.po
In Italian, "to break" can indeed be translated with "interrompere". But
that depends on the context, and this one here is really not the case.
Adopt a sentence which, albeit not a literal translation, sounds a lot
more natural and easier to understand.
FTR, this was reported (by me) as a bug here:
https://bugzilla.opensuse.org/show_bug.cgi?id=1173529
> Improve Italian traslation of the "breaking dependencies" message.

- tests/zypp/PurgeKernels_test.cc
- tests/zypp/data/PurgeKernels/fancybuildnr/solver-system.xml
- tests/zypp/data/PurgeKernels/fancybuildnr/solver-test.xml
- zypp/PurgeKernels.cc
This adds special behaviour for when a kernel version has the rebuild
counter before the kernel commit hash:
`kernel-default-<version>-<release>.<counter>.<hash>`
e.g.:
`kernel-default-5.8.0-3.1.gd4e7682`
> Support buildnr with commit hash in purge-kernels (fixes bsc#1175342)

- tests/zypp/PurgeKernels_test.cc
- tests/zypp/data/PurgeKernels/flavour/@System.repo
- tests/zypp/data/PurgeKernels/flavour/zypp-control.yaml
- zypp/PurgeKernels.cc
Actually this would break with every flavour other than "default"
> Fix bsc#1176902: When kernel-rt has been installed, the purge-kernels service fails during boot

- tests/zypp/RepoStatus_test.cc
- zypp/RepoInfo.cc
- zypp/RepoManager.cc
- zypp/RepoStatus.cc
- zypp/RepoStatus.h
[bsc#1174016](https://bugzilla.suse.com/show_bug.cgi?id=1174016)
The 1st commit solely fixes RepoStatus operator&& to allow joining more then 2 status in arbitrary sequence.
The 2nd one encodes the repo URL in the status and so forces to check the server if local metadata status (incl. the current url) and solv cache status (incl. the url used when creating the cache) don't match.
> Refresh when repourls change

- zypp/target/rpm/RpmDb.cc
- zypp/target/rpm/RpmDb.h
- zypp/target/rpm/librpmDb.cc
- zypp/target/rpm/librpmDb.h
[bsc#1178910](https://bugzilla.opensuse.org/show_bug.cgi?id=1178910)
Prefere an existing database, but follow rpms configured _dbpath if non exists. Assert a compat symlink at /var/lib/rpm exists in case the db is located elsewhere.
> bsc#1178910 fix rpm dbpath

- zypp/PathInfo.cc
- zypp/RepoManager.cc
[bsc#1178966](https://bugzilla.suse.com/show_bug.cgi?id=1178966)
Correctly clean up symlinks in the cache.
> bsc#1178966 fix package cache cleanup

- zypp/KeyManager.cc
- zypp/PublicKey.cc
[bsc#179222](https://bugzilla.suse.com/show_bug.cgi?id=1179222)
> Fix update of gpg keys with elongated expire date (bsc#179222)

- zypp/misc/CheckAccessDeleted.cc
- zypp/target/rpm/librpmDb.cc
[bsc#1178910](https://bugzilla.suse.com/show_bug.cgi?id=1178910)
Creating a librpmDb iterator before/without Target init finds the default dbpath unset and creates a database in /.
(The CheckAccessDeleted commit is unrelated. The numerous but superfluous log lines just caught my eye, because e.g. CheckAccessDeleted checks the installed lsof version and so triggers the above bug).
> bsc#1178910 libzypp wrong dbpath enhanced

- zypp/media/MediaMultiCurl.cc
MultiCurl backend should fall back to a simple download in the case when we do not have a already known filesize and do not receive one from the Metalink data.
This patch implements the correct behaviour.
> Multicurl backend breaks with with unknown filesize (fixes #277)

- zypp/KeyManager.cc
- zypp/target/rpm/RpmDb.cc
Mainly prevent any sichcheck error logging when we do not verify. In that case we just want to get the keys signing a message. The message file itself is /dev/null, so reporting 'bad signature' errors in the log is confusing.
> Minor logging issue regarding gpg keys

- zypp/target/RpmPostTransCollector.cc
The scripts are execuable. No need to call them through 'sh -c'.
> Fix %posttrans script execution (fixes #265)

- zypp/RepoStatus.cc
- zypp/url/UrlBase.cc
This fixes the build in Fedora 34+.
> Add missing includes for GCC 11 compatibility

- zypp/Patch.cc
The result of Patch::isCategory should be the same, no matter if
strings or enum values are compared.
> Patch: Identify well-known category names (bsc#117984)

- tests/zypp/Vendor_test.cc
- zypp/VendorAttr.cc
- zypp/VendorAttr.h
- zypp/solver/detail/SATResolver.cc
[bsc#1182629](https://bugzilla.suse.com/show_bug.cgi?id=1182629) Enable release packages to request a relaxed vendot check in dup.
> dup relaxed vendor check

- zypp/RepoManager.cc
- zypp/ZConfig.cc
- zypp/ZConfig.h
- zypp/base/LogControl.cc
- zypp/base/Logger.h
[bsc#1182936](https://bugzilla.opensuse.org/show_bug.cgi?id=1182936)
Values read from the config file are remembered as default so RM can check whether a cachepath was later amended.
> Do no cleanup in custom cache dirs

- tests/zypp/MediaSetAccess_test.cc
- zypp/media/MediaManager.h
- zypp/repo/RepoProvideFile.cc
- zypp/repo/SUSEMediaVerifier.cc
- zypp/repo/SUSEMediaVerifier.h
[bsc#1180851](https://bugzilla.suse.com/show_bug.cgi?id=1180851)
Reworked the MediaVerifier and relaxed the case where there is just one non-volatile mediun in the set.
> Media set verification issues

- zypp/repo/SUSEMediaVerifier.cc
Unless something changed dramatically recently in C++ - using `static` without `const` or mutex is always thread-unsafe.
> Fix unsafe usage of static in media verifier

- zypp/misc/CheckAccessDeleted.cc
Quick fix for [bsc#1184997](https://bugzilla.opensuse.org/show_bug.cgi?id=1184997)
> Fix sevice detection with cgroupv2

- zypp/MediaSetAccess.cc
[bsc#1185239](https://bugzilla.opensuse.org/show_bug.cgi?id=1185239)
> Properly handle permission denied when providing optional files

- tests/zypp/PurgeKernels_test.cc
- tests/zypp/data/PurgeKernels/withdeps/@System.repo
- tools/zypp-runpurge.cc
- zypp/PurgeKernels.cc
- zypp/misc/YamlTestcaseHelpers.h
Leap 15.3 introduces a new kernel package called kernel-flavour-extra,
which contain kmp's. Currently kmp's are detected by name ".*-kmp(-.*)?"
but this does not work which those new packages. This patch fixes the
problem by checking packages for kmod(*) and ksym(*) provides and only
falls back to name checking if the package in question does not provide
one of those.
> Bug bsc 1185325

- zypp/solver/detail/Resolver.cc
- zypp/solver/detail/Testcase.cc
ZYPP_FULLOG must not write a testcase before a
the solver is actually initialized.
> Fix segv if ZYPP_FULLOG is set (fixes #317)

- needreboot
- zypp/target/TargetImpl.cc
For packages the intended way would be to provide `installhint(reboot-needed)` if the package wants to trigger the needreboot hint.
If the hint should also be shown for packages not providing `installhint(reboot-needed)`, the admin may list them there.
Builtin packages triggering the hint without the provides are kernel and kernel-firmware related.
> Ship an empty /etc/zypp/needreboot per default (fixes #311, jsc#PM-2645)

- zypp/RepoInfo.cc
(fixes openSUSE/zypper#390)
In addition to the effective values, add optional attributes
showing the raw values actually present in the .repo file.
(raw_gpgcheck, raw_repo_gpgcheck, raw_pkg_gpgcheck)
> Enhance XML output of repo GPG options (fixes openSUSE/zypper#390)

- tests/zypp/PurgeKernels_test.cc
- tests/zypp/data/PurgeKernels/rckrnl/@System.repo
- tests/zypp/data/PurgeKernels/rckrnl/zypp-control.yaml
- zypp/PurgeKernels.cc
There recently was a change in the kernel package naming scheme in regards to rc kernels. 
Since kernel upstream uses characters in the version that are not allowed in rpm versions a "-rc" was previously replaced with ".rc" which broke sorting by  version, to fix this issue it was replaced with "~rc", which unfortunately broke the purge-kernels logic. 
This patch makes sure purge-kernel does apply the same conversion.
> Fix bsc#1187738: purge-kernels fails with kernels from Kernel:HEAD

- tests/zypp/RpmPkgSigCheck_test.cc
- zypp/KeyManager.cc
- zypp/KeyManager.h
- zypp/target/rpm/BinHeader.cc
- zypp/target/rpm/BinHeader.h
- zypp/target/rpm/RpmDb.cc
Rpm by default only shows the short key ID when checking the signature
of a package fails. This patch reads the signatures from the RPM headers
and replaces she short IDs with the key fingerprints fetched from the signatures.
> Show key fpr from signature when signature check fails (bsc#1187224) 

- libzypp.spec.cmake
libzypp can build with libressl, too.
> spec: switch to pkgconfig(openssl)

- zypp/zyppng/media/medianetwork.cc
- zypp/zyppng/media/network/networkrequestdispatcher.cc
- zypp/zyppng/media/network/private/downloaderstates/rangedownloader_p.cc
- zypp/zyppng/media/network/private/downloaderstates/rangedownloader_p.h
This patch fixes some issues in the downloader and medianetwork code.
Especially with recursive calling of CURL API which is always a bad idea
> Fix issues in medianetwork

- tools/zypp-rpm/main.cc
- zypp/target/TargetImpl.cc
- zypp/target/rpm/RpmFlags.h
Since we already check signatures and keys in libzypp there is no need
to check them again in the zypp-rpm backend. This patch adds a new
install flag and disables redundant checks in zypp-rpm.
> Do not double check signatures and keys (bsc#1190059)

- CMakeLists.txt
- zypp-core/zyppng/base/statemachine.h
The statemachine needs to make sure a state is not deleted while enter()
was called. This patch should make sure that the states live long
enough.
> Make sure to keep states alives while transitioning (bsc#1190199)

- zypp/PurgeKernels.cc
This change is required for the smooth integration of SLE Live Patching into SLE Micro. The REGEX for kernel-*-livepatch matching might perhaps be improved but I believe that this simple one is enough.
> Fix kernel-*-livepatch removal in purge-kernels

- zypp/zyppng/media/network/private/downloaderstates/basicdownloader_p.cc
A missing check causes zyppng::Downloader to always download full files
even if the checkExistsOnly flag is set. This patch adds the missing
logic.
> Downloader does not respect checkExistsOnly flag (bsc#1190712)

- zypp/PublicKey.cc
- zypp/PublicKey.h
Add a new struct to hold data for signatures on public keys, and use this struct to store signature data on every PublicKeyData. Provide functions to determine whether a signature is trusted or known.
This work is being done with [zypper issue 348](https://github.com/openSUSE/zypper/issues/348) in mind.
> WIP: Store key signatures on public keys

- tools/zypp-NameReqPrv.cc
- tools/zypp-rpm/main.cc
- zypp-core/zyppng/io/asyncdatasource.h
- zypp/ProgressData.cc
- zypp/ZYppCallbacks.h
- zypp/target/RpmPostTransCollector.cc
- zypp/target/TargetImpl.cc
- zypp/target/rpm/RpmDb.cc
- zypp/zyppng/media/network/private/downloaderstates/detectmeta_p.h
A few unrelated commits at the beginning.
Enhanced rpm script output reports to offer output lines immediately. Zypper will be enhanced to show them immediately rather than showing the collected output at the end.
For singetrans a new report is used to propagate the (debug)lines issued from the rpmlog subsystem.  Zypper will be enhanced to show them in addition to sny script output.
> Some enhancements around reporting (traditional rpm and singletrans)

- zypp/media/MediaISO.cc
There is no need to fiddle with the encoding. If the iso: URL has a
url= embedded in the query part, the retrieved value must be a valid
- special chars encoded - URL. And if the retrieved iso= filename
contains special chars (spaces,etc.), Url::setPathName will properly
encode them. There should be no need for any manual url::encode call.
> Fix wrong encoding of iso: URL components (bsc#954813)

- zypp/target/TargetImpl.cc
Deserializing a 32bit value into a 64bit variable is not giving the correct result on big endian architectures. This patch should fix the issues with singletrans on s390
> Fix serializing/deserializing type mismatch in zypp-rpm protocol (bsc#1196925)

- tests/zyppng/io/AsyncDataSource_test.cc
- zypp-core/zyppng/io/asyncdatasource.cpp
- zypp-core/zyppng/io/asyncdatasource.h
- zypp/target/TargetImpl.cc
In cases where librpm would not send a finalize message about a running
transaction step (RPMCALLBACK_*_STOP), zypp-rpm would not finalize the
report by sending the end of script tag. Adding another stop condition to
the wait loop when the communication pipe is closed should fix the
problem.
> Fix possible hang in singletrans mode (bsc#1197134)

- zypp/sat/Solvable.h
May happen if (wrong arch) solvables were removed at the beginning
of the repo.
> Work around cases where sat repo.start points to an invalid solvable

- zypp/media/MediaCurl.cc
[bsc#1199042](https://bugzilla.opensuse.org/show_bug.cgi?id=1199042)
Do not wait until the first data arrived.
> Immediately start monitoring the download.transfer_timeout 

- zypp/base/DrunkenBishop.cc
Resolves:
```
/home/abuild/rpmbuild/BUILD/libzypp-17.30.3/zypp/base/DrunkenBishop.cc:30:18: error: use of enum 'Direction' without previous declaration
30 |       enum class Direction : std::uint8_t       // actually 2 bits
```
Fixes: #396
> Fix building with GCC 13.

- zypp/ZYpp.h
I am using ```boost 1.80``` and it has an issue during the ```make``` process. The issue is below:
```
In file included from /home/hui-zhi/projects/src/github.com/openSUSE/libzypp/zypp/ZYppFactory.h:18:0,
from /home/hui-zhi/projects/src/github.com/openSUSE/libzypp/zypp/misc/DefaultLoadSystem.cc:19:
/home/hui-zhi/projects/src/github.com/openSUSE/libzypp/zypp/ZYpp.h:156:17: error: declaration of ‘void boost::checked_delete(T*) [with T = zypp::ZYpp]’ has a different exception specifier
friend void ::boost::checked_delete<ZYpp>(ZYpp*); // template<class T> inline void checked_delete(T * x)
^~
In file included from /usr/local/lib/boost/include/boost/smart_ptr/detail/sp_counted_impl.hpp:27:0,
from /usr/local/lib/boost/include/boost/smart_ptr/detail/shared_count.hpp:27,
from …
```
> fix: boost::checked_delete(T*) has a different exception specifier

- zypp/RepoInfo.cc
- zypp/RepoInfo.h
- zypp/RepoManager.cc
- zypp/repo/Downloader.cc
- zypp/repo/yum/Downloader.cc
This patch allows zypp to skip a extra media.1/media download to calculate if a repository needs to be refreshed. This optimisation only takes place if the repo does specify only downloading base urls.
> Skip media.1/media download for http repo status calc

- zypp/repo/SUSEMediaVerifier.cc
This patch disables media checks if a media set has only 1 medium and the URL has a downloading scheme ( e.g. http,https, ftp etc ). This lowers the number of connects to the download servers.
> Do not verify a medium in certain cases

- zypp/repo/yum/Downloader.cc
This patch fixes a issue with the deltafile lookup, only a relative path was returned which broke the deltafile code in the downloader backends.
> Return a absolute path if a deltafile was found

- zypp/MediaSetAccess.cc
- zypp/media/MediaCurl.cc
- zypp/media/MediaCurl.h
Avoid an additional HEAD request to check whether the file is actually present. To avoid failing progress reports in case the optional file is not present, the progress report start is delayed until we actually receive some data.
> Improve download of optional files (fixes #416)

- zypp/RepoManager.cc
Due to a exception handler scope the MediaSetAccess handle was cleaned up too early, causing the file to vanish before it was parsed.
> Do not clean up MediaSetAccess before using the geoip file

- zypp/media/MediaCurl.cc
[bsc#1204548](https://bugzilla.suse.com/show_bug.cgi?id=1204548)
Stupid C error. All the error handling locations properly reset the head/range request curl settings. But the most important case, when the task succeeded, failed to reset the range request. Subsequent tasks using the same curl handle continue to request just 2 byte. Fortunately this happens only if `?head_requests=no` is set in the URL.
Now using a RAII guard to make sure the options are reset no matter how the function is left.
> Properly reset range requests

- zypp/media/MediaMultiCurl.cc
In some cases the MultiCurl backend can fall back to a normal Curl download, but if this happens after a metalink file was completely downloaded the progress function must be resetted to the default progress callback. Otherwise the alive callback is used which does not show any percentage updates.
> MultiCurl: Make sure to reset the progress function when falling back

- zypp-core/zyppng/io/private/socket_p.h
- zypp-core/zyppng/io/socket.cc
This patch hopefully fixes logging on WSL, getsockopt seems to not be fully supported but the code required it when accepting new socket connections. However we already know the required infos ( domain, protocol, type ) from the listening socket that accepts the incoming connections.
> Avoid calling getsockopt when we know the info already

- zypp/RepoManager.cc
- zypp/RepoManager.h
- zypp/base/Algorithm.h
This patch updates the geoip code to only contact the server for geoip data if the refreshing repository uses a configured geoip hostname in it's repodata.
> Only refresh geoip if a geoip host is used

- doc/autoinclude/EnvironmentVariables.doc
- zypp-curl/curlhelper.cc
- zypp-curl/parser/metalinkparser.cc
- zypp-curl/parser/zsyncparser.cc
[bsc#1127591](https://bugzilla.opensuse.org/show_bug.cgi?id=1127591)
fixes #335
> multicurl: propagate ssl settings stored in repo url

- zypp-media/mediaconfig.cc
- zypp.conf
Maximum time in seconds that you allow the connection phase to the server to take. This only limits the connection phase, it has no impact once it has connected. (see also CURLOPT_CONNECTTIMEOUT)
> zypp.conf: Introduce 'download.connect_timeout' [60 sec.] (bsc#1208329)

- zypp-curl/transfersettings.cc
- zypp-curl/transfersettings.h
- zypp/media/MediaCurl.cc
HTTP/2 RFC 9113 forbids fields ending with a space. Violation results in curl error: 92: HTTP/2 PROTOCOL_ERROR.
> curl: Trim user agent string (bsc#1212187)

- zypp-curl/ng/network/request.cc
- zypp-curl/transfersettings.cc
- zypp-curl/transfersettings.h
- zypp/media/MediaCurl.cc
HTTP/2 RFC 9113 forbids fields ending with a space. So we make sure custom headers are trimmed.
> Curl: trim custom headers (bsc#1212187)

- zypp/ZYppFactory.cc
[bsc#1213231](https://bugzilla.suse.com/show_bug.cgi?id=1213231)
The commit partially reverts 678f8e9a4eaf4cc834c6784e58dd3fd2ca0bc3fe.
> Fix negative ZYPP_LOCK_TIMEOUT not waiting forever

- tools/DownloadFiles.cc
- zypp-curl/ng/network/private/downloaderstates/basicdownloader_p.cc
- zypp-curl/ng/network/private/downloaderstates/metalinkinfo_p.cc
In some cases when downloading very small files we can run into issues when the URL
is protected by credentials:
Curl will by default first try to send a request without credentials to the server
and only if the server responds with HTTP-401, Curl issues a 2nd request this time
including the configured credentials.
Until Curl detects this situation it will call the progress callback with the currently
downloaded bytes in the request. So if the server sends a big payload with the HTTP-401
response the code triggered the FileSizeExceeded error and cancelled.
This patch works around this issue by checking against the bytes
actually written into the target file instead of dlnow reported by Curl.
> Fix bsc 1213673

- zypp-tui/output/Out.h
- zypp/Arch.h
Clang seems to have issues with picking the overload in std::men_fn if there is a static overload of a member function. We need to explicitely specify the correct type of the function pointer.
To make sure this would not break compiling a application with clang that builds against libzypp this patch works around the problem.
> Fix zypp/Arch.h for clang (fixes #478)

- zypp-core/base/inputstream.h
- zypp/target/RpmPostTransCollector.cc
- zypp/target/RpmPostTransCollector.h
- zypp/target/TargetImpl.cc
- zypp/target/rpm/RpmDb.cc
- zypp/target/rpm/RpmDb.h
- zypp/target/rpm/RpmHeader.cc
- zypp/target/rpm/RpmHeader.h
[bsc#1041742](https://bugzilla.suse.com/show_bug.cgi?id=1041742)
The initial commits pass the existing `RpmPostTransCollector` down to the `RpmDB` layer and provide a new `RpmDb::runposttrans` call for a delayed execution of  `%posttrans` and `%transfiletrigger(postun|in) `scripts.
Then `RpmPostTransCollector` is adapted to collect either `%posttrans` scripts or  `dump_posttrans:` lines, depending on what rpm supports. `RpmPostTransCollector::executeScripts` is adapted accordingly. Execution of `%posttrans` scripts by libzypp itself is intentionally not interruptible via callbacks because the same is true for `rpm --runposttrans` execuition.
Todo:
> Use --runposttrans if rpm supports it

- zypp/target/rpm/RpmHeader.cc
```
/<<PKGBUILDDIR>>/zypp/target/rpm/RpmHeader.cc: In function ‘int unameToUid(const char*, uid_t*)’:
/<<PKGBUILDDIR>>/zypp/target/rpm/RpmHeader.cc:41:16: error: ‘strcmp’ was not declared in this scope
41 |     } else if (strcmp(thisUname, "root") == 0) {
```
> Add missing include to fix build failure with new compiler in Debian

- cmake/modules/Findlibproxy.cmake
Semantics of PKG_SEARCH_MODULES seems to have changed with more recent cmake versions, use PKG_CHECK_MODULES instead.
> Fix discovery of libproxy on newer cmake

- zypp-tui/output/Out.cc
Observed (on a 80-wide terminal):
The <x%> tag does not move in the first 7%, while it does move in the last 7%. Printing the <50%> state shows 29 dots and 35 equals signs. The <10%> state even goes backwards compared to <9%>.
```
abcdefg <1%>=================================================================[/]
abcdefg <3%>=================================================================[-]
abcdefg <5%>=================================================================[\]
abcdefg <7%>=================================================================[|]
abcdefg ..<9%>===============================================================[/]
abcdefg .<10%>===============================================================[-]
abcdefg .............................<50%>===================================[\] …
```
> Fix ProgressBar's calculation of the printed tag position

- zypp-tui/output/OutNormal.cc
This reverts the code originally added in zypper's commit f141cf5579a460cb46093dfa130f25b03efaefce and which was later moved to libzypp.
Cyan is already used for the output of RPM scriptlets. Avoid this colorific collision between download progress bar and scriptlet output. See
https://github.com/openSUSE/zypper/pull/475#issuecomment-1382740585 for picture.
The download bar is already distinguishable from the preceding status line by the long streak of dashes/dots.
> Revert "Color download progress bar"

- tools/CMakeLists.txt
- tools/DownloadFiles.cc
I was just browsing commits and thought…
libzypp already contains a progress bar, no need to roll our own. (Demote PCBar to an adapter class.)
References: https://github.com/openSUSE/libzypp/issues/489
> tools/DownloadFiles: use standard zypp progress bar

- zypp/target/RpmPostTransCollector.cc
[bsc#1216412](https://bugzilla.suse.com/show_bug.cgi?id=1216412). If rpm warnings are issued on dbopen, this should at least reduce their amount.
> Open rpmdb just once during execution of %posttrans scripts

- zypp/RepoManager.cc
- zypp/RepoManager.h
- zypp/parser/RepoFileReader.cc
- zypp/parser/ServiceFileReader.cc
[bsc#1212160](https://bugzilla.suse.com/show_bug.cgi?id=1212160)
Convenient and helps documentation as it may refer to a single command for a bunch of distributions. 
Like e.g.`zypper ar 'https://server.my/$releasever/my.repo'`
> Expand RepoVars in URLs downloading a .repo file

- zypp/target/TargetImpl.cc
We need this for the boot plugin in order to speed up the boot process after transactional update. 
Otherwise no commit plugin will be called. 
We have already had discussed this in the Chat:
"The typical --root use case is a bare metal installation, where no inner plugins are available at all. So no one missed it. At least no one asked for it.
We have no means to detect whether the inner plugin and the outer libzypp fit together (on protocol level). OTOH it's a one-way communication anyway. The plugin is not able to influence libzypp's behavior. If it does not speak our language it's killed.
If it's important for you, we have bool isTransactionalServer = ( fsinfo.f_type == BTRFS_SUPER_MAGIC && PathInfo( "/usr/sbin/transactional-update" ).isFile() );.  It should be doable to enable the …
> Calling zypp commit plugins if zypp will be called while an transactional update

- zypp/misc/CheckAccessDeleted.cc
[bsc#1218291](https://bugzilla.suse.com/show_bug.cgi?id=1218291)
> CheckAccessDeleted: fix 'running in container' filter

- zypp/zypp_detail/ZYppImpl.cc
- zypp/zypp_detail/ZYppImpl.h
This patch changes zypp-poll to use the original read fd of the shutdown pipe, otherwise it would be duplicated every time which is just unnecessary overhead.
> Avoid calling ::dup in zypp-call

- po/th.po
- Add more translation of country and language names, using Unicode Common Locale Data Repository (CLDR) version 44 https://cldr.unicode.org/
- Remove prefix "ภาษา" ("language") from some language names, for consistency with others and follow Unicode CLDR
- Remove language name translations that are clearly wrong (probably from machine translation - a lot of them are translated as the same string `"เป็นก_ลุ่มภาษา"`)
- Fix some %d, %s, %1 agreements
- Fix few typos
> [L10n] Update th.po - add more country/lang name translations

- zypp/misc/CheckAccessDeleted.cc
[bsc#1218782](https://bugzilla.suse.com/show_bug.cgi?id=1218782)
This restores the previous behavior - which was known to work for flatpacks - for /proc/PID/fd symlinks pointing to a file (i.e. readlinkd returning an absolute path). Only links to pipe or socket 'type:[inode]' or an 'anon_inode:<file-type>' are ignored.
> CheckAccessDeleted: fix running_in_container detection

- zypp/ProblemSolution.cc
- zypp/ProblemSolution.h
- zypp/solver/detail/SolutionAction.cc
- zypp/solver/detail/SolutionAction.h
Libzypp intentionally does not expose `SolutionAction`, so we offer it in `ProblemSolution`.
> Add ProblemSolution::skipsPatchesOnly (for openSUSE/zypper#514)

- zypp/target/TargetImpl.cc
Just the combination --dry-run --download-only will download packages in order to perform a file-conflict check.
@bzeller did we have a bug or issue number for this?
> Prevent SINGLE_RPMTRANS from downloading packages if --dry-run.

- needreboot
Just a fix for a small typo:   
```administartor -> administrator```
> Fix a typo

- zypp/media/MediaCurl.cc
- zypp/media/MediaCurl.h
- zypp/media/MediaMultiCurl.cc
strncpy() does not terminate a string that is excessively long, which triggers a compiler warning with gcc 13. add setCurlError function that encapsulates the termination.
> Fix strncpy() string concatenation warning

- zypp-tui/Table.cc
- zypp-tui/Table.h
- zypp-tui/output/Out.cc
- zypp-tui/output/Out.h
- zypp-tui/output/OutNormal.cc
- zypp/CMakeLists.txt
Public header files must not expose zypp-core/base/Gettext.h! (any!, not just zypp-tui's)
Otherwise our gettext macros may accidentally overwrite the application's macros, or get overwritten by the application's. Both leads to text being looked up in the wrong textdomain.
> zypp-tui: Make sure translated texts use the correct textdomain

- tests/zyppng/media/Provider_test.cc
- zypp-core/zyppng/core/string.h
This patch fixes a issue in safe_strtonum which caused timestamps to overflow in the Provider message parser.
> Fix int overflow in Provider (fixes #559)

- zypp-core/base/Easy.h
libzypp requires C++17.
The condition is not working for Clang.
> Do not hide nullptr

- CMakeLists.txt
- libzypp.spec.cmake
Newer versions of CMake warn that support for CMake < 3.5 is deprecated.
> Require CMake 3.5

- cmake/modules/FindRpm.cmake
With CMake 3.1, which is the required minimum version of libzypp, policy CMP0054 is always set to NEW. No need to set it explicitly.
See https://cmake.org/cmake/help/latest/policy/CMP0054.html
> [cmake] Do not set CMP0054 it is always NEW

- zypp/misc/CheckAccessDeleted.cc
- zypp/target/CommitPackageCache.cc
- zypp/target/RpmPostTransCollector.cc
- zypp/target/TargetImpl.cc
- zypp/target/rpm/librpmDb.cc
- zypp/target/rpm/librpmDb.h
After deprecating the db_const_iterator default ctor, the fix is straight forward. 
Either we need / or we need to follow the current RpmDb.
The test however shows too any dbopen/close calls. I'll add a fix for this ASAP.
> fix rpmdb iterator usage

- .gitignore
- zypp-glib/repomanager.h
With the fix, I am now able to generate proper rust bindings for all structs used in gir files.
> Zyppng staging fix zypp task status

- zypp-glib/CMakeLists.txt
Without change the library is not installed as part of make install when glib is enabled.
> Fix glib install

- tests/lib/CMakeLists.txt
- tests/lib/WebServer.cc
On Debian and derivatives the fcgi headers are not stored in a fastcgi/ subdirectory:
https://packages.debian.org/trixie/amd64/libfcgi-dev/filelist
> cmake: check location of fcgi header and adjust include accordingly

- tests/zypp/Url_test.cc
- zypp-core/Url.cc
- zypp-core/url/UrlBase.cc
- zypp-core/url/UrlBase.h
- zypp-core/url/UrlUtils.cc
- zypp-core/url/UrlUtils.h
([bsc#1234304](https://bugzilla.suse.com/show_bug.cgi?id=1234304))
> Url query part: `=` is a safe char in value

- zypp-core/base/LogControl.cc
- zypp/ZYpp.h
- zypp/target/RpmPostTransCollector.cc
Preparation for a future switch of `boost::*_ptr` to C++11 `std::*_ptr`. This needs care and a transition as software using libzypp needs adaption.
*_ptr = shared_ptr, scoped_ptr, weak_ptr, intrusive_ptr
> Only use zypp::*_ptr instead of boost::*_ptr

- tools/zypp-pubkey.cc
- zypp-common/private/keyring_p.cc
- zypp-core/ExternalProgram.cc
- zypp-core/base/Easy.h
- zypp-core/base/String.h
- zypp-curl/proxyinfo/proxyinfoimpl.h
- zypp-media/auth/credentialmanager.cc
* I did not remove the now unused `for_each_` for possible external uses. Should I remove it?
* I just removed some uses of `for_`. More are following once this is merged.
> Remove some of the pre-C++11 macros to emulate range-base for loops

- zypp.conf
- zypp/ZConfig.cc
- zypp/ZConfig.h
- zypp/ZYppFactory.cc
If zypp is locked by another process this is the number of seconds to wait for the lock to become available. A negative value will wait forever. If the lock can not be acquired within the specified time an exception is raised. The setting may be overwritten by the ZYPP_LOCK_TIMEOUT environment variables
> zypp.conf: Add `lock_timeout` ($ZYPP_LOCK_TIMEOUT) (bsc#1239809)

- zypp/zypp_detail/ZYppImpl.cc
[bsc#1246912](https://bugzilla.suse.com/show_bug.cgi?id=1246912)
Between update of a baselib it's subarch packages ld.so loads the subarch extension although it does not fit the baselib. To avoid breking commands, we disable loading subarch extensions during install.
> Make ld.so ignore the subarch packages during install

- zypp-logic/zypp/ng/repo/workflows/repodownloaderwf.cc
- zypp-logic/zypp/ng/repo/workflows/repomanagerwf.cc
- zypp-logic/zypp/ng/workflows/checksumwf.cc
- zypp-logic/zypp/ng/workflows/repoinfowf.cc
- zypp-logic/zypp/target/TargetCallbackReceiver.h
- zypp/zypp-tui/utils/ansi.h
- zypp/zypp/media/MediaPriority.cc
- zyppng/lib/zypp-media/ng/worker/mountingworker.h
- zyppng/tools/zypp-media-tvm/testvmprovider.h
Some are only part of `-Wall` or `-Wpedantic`.
> Reduce number of Clang warnings
