zypp.conf
Fixes two smaller typos I stumbled upon reading zypp.conf. :)
=> Fix typos in zypp.conf

zypp/target/modalias/Modalias.cc
Reduce the number of ::lstat calls by evaluating dirent.d_type and
unify retrieved set of modalias strings.
=> Enhance scanning /sys for modaliases (bsc#1130161)

zypp/misc/CheckAccessDeleted.cc
New algorithm that detects if a given PID is running inside a container.
The previous one just took the PID namespace into account, however that
could be misleading since containers can share the PID namespace with
the Host.
Fixes bsc#1146947
=> New container detection algorithm for zypper ps

zypp.conf, zypp/CMakeLists.txt, zypp/Resolver.cc, zypp/Resolver.h, zypp/ResolverFocus.cc, zypp/ResolverFocus.h, zypp/ZConfig.cc, zypp/ZConfig.h, zypp/solver/Types.h, zypp/solver/detail/Resolver.cc, zypp/solver/detail/Resolver.h, zypp/solver/detail/SATResolver.cc, zypp/solver/detail/SATResolver.h, zypp/solver/detail/Testcase.cc
[bsc#1146415](https://bugzilla.suse.com/show_bug.cgi?id=1146415)
Provide `ResolverFocus` flags. Allow to set the default in `zypp.conf`; Resolver API to change it; remember current setting in testcases.
=> Set resolver focus

zypp/PathInfo.cc, zypp/PathInfo.h, zypp/media/MediaCurl.cc
[bsc#1158763](https://bugzilla.suse.com/1158763)
=> Fix cookies file permission

zypp/CheckSum.h, zypp/OnMediaLocation.cc, zypp/OnMediaLocation.h, zypp/Patch.h, zypp/Pathname.h, zypp/base/Easy.h, zypp/base/String.h, zypp/repo/RepoVariables.h, zypp/sat/SolvableType.h
1st commit is just cleanup.
The 2nd one switches OnMediaLocation to use COW and adds get/set for zchunk header size/checksum.
=>  OnMediaLocation: Switch implementation to RWCOW_pointer 

zypp/AutoDispose.h, zypp/CMakeLists.txt, zypp/base/ExternalDataSource.cc, zypp/base/ExternalDataSource.h, zypp/base/IOTools.cc, zypp/base/IOTools.h, zypp/misc/CheckAccessDeleted.cc, zypp/target/rpm/RpmDb.cc
This patch adds helpers to time out when waiting for external process data
=> Add timout io

doc/autoinclude/SolverVendorChange.doc, tests/zypp/Vendor_test.cc, zypp.conf, zypp/VendorAttr.cc, zypp/VendorAttr.h
The missing VendorAttr rewrite....
=> VendorAttr rework

zypp/RepoInfo.cc, zypp/VendorAttr.h
Two small enhancements for the next release.
=> repo type handling, etc.

tests/sat/LookupAttr_test.cc
=> adapt testcase to change introduced by libsolv#402

tests/zypp/Url_test.cc, zypp/RepoInfo.cc, zypp/ServiceInfo.cc, zypp/Url.cc, zypp/Url.h, zypp/base/StringV.cc, zypp/repo/RepoVariables.cc, zypp/url/UrlBase.cc, zypp/url/UrlBase.h
1st draft stripping the proxpass except. within the .repo file.
And repo var replacement still needs to be checked.
=> Ma 1050625 proxy credentials written to log files

needreboot, zypp/target/TargetImpl.cc
[bsc#1179083](https://bugzilla.suse.com/show_bug.cgi?id=1179083)
=> needreboot: remove udev from the list

tests/zypp/base/CMakeLists.txt, tests/zypp/base/ExternalProgram_test.cc, zypp/base/IOTools.cc, zypp/misc/CheckAccessDeleted.cc
[bsc#1179909](https://bugzilla.suse.com/show_bug.cgi?id=1179909)
=> Fix lsof monitoring (bsc#1179909)

tests/zypp/StringV_test.cc, zypp/base/StringV.cc, zypp/base/StringV.h
Refactoring commit is just to ease split tests. Trim commit is quite independent.
=> String_view split rewrite, trim added

zypp/target/TargetImpl.cc
[bsc#1181328](https://bugzilla.suse.com/show_bug.cgi?id=1181328)
Some systemd tools require /proc to be mounted and fail if it's not there.
=> Try to provide a mounted /proc in --root installs (bsc#1181328)

zypp/PoolQuery.cc, zypp/PoolQuery.h
Fix https://github.com/openSUSE/zypper/issues/388
=> Add comment option for lock command

tools/zypp-rpm/errorcodes.h, tools/zypp-rpm/main.cc, zypp/target/TargetImpl.cc
- Use equivalents of --force and --nodeps for now
- Fix a out of range access in report handling 
- Execute rpmtsorder to support exotic rpm ordering
=> Fixing small issues with singletrans mode

zypp-core/Url.cc, zypp-core/Url.h, zypp/RepoManager.cc
[bsc#1191286](https://bugzilla.suse.com/show_bug.cgi?id=1191286)
=> RepoManager: Don't probe for plaindir repo if URL schema is plugin

zypp.conf, zypp/Callback.h, zypp/KeyRing.cc, zypp/Locks.h, zypp/RepoInfo.cc, zypp/Resolver.h, zypp/ZYppCallbacks.h
Changed several gendered pronouns (mostly 'he' to 'it') and a few spelling errors that jumped out as me as well.
=> Changed gendered pronouns to be gender-neutral, and spelling errors

zypp/ZConfig.cc
[bsc#1193488](https://bugzilla.suse.com/show_bug.cgi?id=1193488)
=> Use the default zypp.conf settings if no zypp.conf exists (bsc#1193488)

CMakeLists.txt, zypp-core/CMakeLists.txt, zypp-core/base/Exception.cc, zypp-core/base/StringV.h, zypp-core/zyppng/io/abstractspawnengine.cc, zypp-core/zyppng/io/forkspawnengine.cc, zypp-core/zyppng/io/private/forkspawnengine_p.h, zypp-curl/CMakeLists.txt, zypp-media/CMakeLists.txt, zypp/CMakeLists.txt, zypp/RepoManager.cc
On the fly a few commits to adjust the log groups.
=> Enhance 'failed to cache repo' reporting

zypp-media/auth/credentialmanager.cc
https://bugzilla.suse.com/show_bug.cgi?id=1194898
=> Fix exception handling when reading or writing credentials (bsc#1194898)

zypp-core/ExternalProgram.cc, zypp-core/zyppng/io/forkspawnengine.cc, zypp/sat/detail/PoolImpl.cc
[(bsc#1195326)](https://bugzilla.suse.com/show_bug.cgi?id=1195326)
(the PoolImpl commit is unrelated; just to decrease solvers logging)
=> Fix handling of redirected command in  output

zypp/solver/detail/SATResolver.cc
[bsc#1194848](https://bugzilla.suse.com/show_bug.cgi?id=1194848)
=> Hint on ptf<>patch resolver conflicts

zypp/media/MediaManager.cc
ReleaseAll must remove stacked media first. Otherwise a still mounted iso may prevent unmounting the parent.
=> Fix handling of ISO media in releaseAll (bsc#1196061)

doc/autoinclude/FeatureTest.doc, doc/autoinclude/Plugins.doc, libzypp.spec.cmake, zypp-core/base/Exception.h, zypp-core/fs/watchfile.h, zypp/CMakeLists.txt, zypp/Fetcher.cc, zypp/RepoManager.cc, zypp/repo/Downloader.cc, zypp/repo/Downloader.h, zypp/repo/PluginRepoverification.cc, zypp/repo/PluginRepoverification.h
Allow e.g. a rekor plugin being hooked into repo refresh to perform additional verification beyond GPG.
=> Basic repo verification plugin

zypp/base/Random.cc
Add missing header file.
Fixes: #396
=> Fix building with GCC 12.x release.

zypp/media/MediaMultiCurl.cc
When not receiving a blocklist via metalink file from the server MediaMultiCurl used to fallback to a fixed, relatively small BLKSIZE. This patch changes the fallback into a dynamic value based on the filesize using a similar metric as the MirrorCache implementation on the server side.
=> Use a dynamic fallback for BLKSIZE in downloads

zypp/RepoManager.cc
[bsc#1204956](https://bugzilla.opensuse.org/show_bug.cgi?id=1204956)
In conjunction with `--keep-packages` set for the repositories, downloaded packages will stay in the package cache, even if repositories are removed or no longer present on the system. Explicit `zypper clean` is not affected (will clean the packages).
If this is actually desired: `touch /var/cache/zypp/packages/.no_auto_prune`
(for libzypp-17.31.5)
=> '.no_auto_prune' in the package cache dir prevents auto cleanup

zypp/ShutdownLock.cc, zypp/sat/WhatProvides.h, zypp/solver/detail/Resolver.cc, zypp/solver/detail/SATResolver.cc, zypp/solver/detail/SATResolver.h
Cleanup in solver code and [bsc#1203248](https://bugzilla.opensuse.org/show_bug.cgi?id=1203248)
=> Removing a PTF without enabled repos should always fail

tests/zypp/ProgressData_test.cc, zypp-core/ui/progressdata.cc, zypp/ZYppCallbacks.h
[bsc#1206949](https://bugzilla.opensuse.org/show_bug.cgi?id=1206949)
=> bsc#1206949: sanitize progress report

zypp-core/base/LogTools.h, zypp-core/base/Logger.h, zypp-core/base/StringV.cc, zypp-core/base/StringV.h, zypp-curl/curlhelper.cc, zypp-curl/ng/network/private/request_p.h, zypp-curl/ng/network/request.cc, zypp-curl/private/curlhelper_p.h, zypp/media/MediaCurl.cc, zypp/media/MediaCurl.h
A few fixes and a common setup of CURLOPT_DEBUGFUNCTION
=> Zypp media curl debug

tests/zypp/CheckSum_test.cc, tools/zypp-media-disk/diskprovider.cc, zypp-core/zyppng/rpc/messagestream.h, zypp-curl/ng/network/private/downloaderstates/preparemulti_p.cc, zypp/MediaSetAccess.cc, zypp/sat/SolvAttr.h, zypp/solver/detail/SATResolver.cc
Fixes compiler warnings mostly about dangling references and some others I came across that didn't look healthy.
=> Fix compiler warnings dangling ref

zypp/RepoInfo.cc, zypp/media/MediaCurl.cc
[bsc#1210870](https://bugzilla.suse.com/show_bug.cgi?id=1210870).
The issue was introduced in 25688b7f6da7a8ab2ef3ec2f68f4df86ff85e4b5.  Moving `retry = false;` to the start of the do-loop was a bad idea because the call to `authenticate` _abused_ `retry == false` to indicate it's first invocation, which returns any stored credentials.
(the 1st commit is unrelated. the superfluous error messages in the log just caught my eye)
=> MediaCurl: Fix endless loop if wrong credentials are stored in credentials.cat

libzypp.spec.cmake
remove duplicate file listing .pc file
=> libzypp.spec.cmake: remove duplicate file listing

zypp/RepoManager.cc
[bsc#1210740](https://bugzilla.suse.com/show_bug.cgi?id=1210740)
=> Don't cleanup orphaned dirs if read-only mode was promised

zypp.conf
=> fix comment typo on zypp.conf

libzypp.spec.cmake, tests/data/nginxconf/nginx.conf, tests/data/vsftpconf/vsftpd.conf, tests/lib/CMakeLists.txt, tests/lib/FtpServer.cc, tests/lib/FtpServer.h, tests/zypp/MediaSetAccess_test.cc, tests/zyppng/media/EvDownloader_test.cc, tests/zyppng/media/NetworkRequestDispatcher_test.cc, tools/DownloadFiles.cc, zypp-core/Digest.cc, zypp-core/Digest.h, zypp-core/base/IOTools.cc, zypp-core/base/IOTools.h, zypp-curl/CMakeLists.txt, zypp-curl/ng/network/curlmultiparthandler.cc, zypp-curl/ng/network/curlmultiparthandler.h, zypp-curl/ng/network/private/downloaderstates/basicdownloader_p.cc, zypp-curl/ng/network/private/downloaderstates/metalinkinfo_p.cc, zypp-curl/ng/network/private/downloaderstates/metalinkinfo_p.h, zypp-curl/ng/network/private/downloaderstates/rangedownloader_p.cc, zypp-curl/ng/network/private/downloaderstates/zck_p.cc, zypp-curl/ng/network/private/request_p.h, zypp-curl/ng/network/request.cc, zypp-curl/ng/network/request.h, zypp-curl/parser/metadatahelper.cc, zypp-curl/parser/metadatahelper.h, zypp/media/MediaMultiCurl.cc, zypp/media/MediaMultiCurl.h
This PR adds the ability to multicurl to fetch multiple chunks with the same request using http multirange until it reaches a default chunk size based on the size of the downloaded file. 
Also enables zsync support.
=> ZSync + HTTP multirange requests in MultiCurl

po/th.po
- Update country names in Thai to use the official spelling from the Office of the Royal Society of Thailand
- Add some missing translations
- Fix few typos
=> [L10n] Update th.po - more translations

zypp/repo/Applydeltarpm.cc
[bsc#1219442](https://bugzilla.suse.com/show_bug.cgi?id=1219442)
=> applydeltaprm: Create target directory if it does not exist

zypp/media/MediaMultiCurl.cc
Due to ongoing issues with download speed, a minimum chunk/stripe download size is required to prevent conflict with TCP slowstart/congestion control.
I'm not 100% sure the patch is correct, the logic in this section is very convoluted and hard to follow. The idea is that if the calculated default blocksize is too small then we set it to a larger value. This way smaller files download in a single shot, but larger ones are chunked over multiple mirrors with a chunk size reasonable enough to actually get a TCP connection to it's full speed.
=> Add default stripe minimum

tests/data/vsftpconf/vsftpd.conf
=> Tests: fix vsftpd.conf where SUSE and Fedora use different defaults

zypp/Resolver.cc, zypp/Resolver.h, zypp/solver/detail/Resolver.cc, zypp/solver/detail/Resolver.h, zypp/solver/detail/SATResolver.cc, zypp/solver/detail/SATResolver.h
[bsc#1221525](https://bugzilla.suse.com/show_bug.cgi?id=1221525)
=> Add resolver option 'removeOrphaned' for distupgrade

zypp-core/fs/PathInfo.cc, zypp-core/fs/PathInfo.h, zypp-core/fs/TmpPath.cc, zypp-core/fs/TmpPath.h, zypp/ng/repo/refresh.cc
[bsc#1222398](https://bugzilla.suse.com/show_bug.cgi?id=1222398)
=> Fix raw cache permissions

zypp/RepoManager.cc
[bsc#1223094](https://bugzilla.suse.com/show_bug.cgi?id=1223094)
=> Don't try to refresh volatile media as long as raw metadata are present

zypp/pool/PoolImpl.h
[bsc#1225267](https://bugzilla.suse.com/show_bug.cgi?id=1225267)
Buddy pairs (like -release package and product) internally share the same status object. When applying locks from query results the locked bit must be set if either item is locked.
=> Fix handling of buddies when applying locks

tools/zypp-rpm/main.cc
[bsc#1228647](https://bugzilla.suse.com/show_bug.cgi?id=1228647)
=> Rpm db issues after zypper source install with single rpmtrans backend

zypp-core/rpc/PluginFrame.cc
According to the STOMP protocol it would be correct to escape a colon in a header-value, but it breaks plugin receivers which do not expect this. The first colon separates header-name from header-value, so escaping in the header-value is not needed anyway.
Escaping in the header-value affects especially the urlresolver plugins. The input URL is passed in a header, but sent back as raw data in the frames body. If the plugin receiver does not correctly unescape the URL we may get back a "https\c//" which is not usable.
=> PluginFrame: Send unescaped colons in header values (bsc#1231043)

zypp-curl/curlhelper.cc, zypp-curl/parser/mediablocklist.cc, zypp/target/TargetImpl.cc
=> Fix four sign-compare warnings

zypp-core/fs/PathInfo.h, zypp/ng/repo/workflows/repomanagerwf.cc
=> Fix missing UID checks in repomanager workflow

zypp/ZYppCommitPolicy.cc
[bsc#1236481](https://bugzilla.suse.com/show_bug.cgi?id=1236481), [bsc#1189788](https://bugzilla.suse.com/show_bug.cgi?id=1189788)
Commit will amend the backend in case the transaction would perform a filesystem usrmerge.
=> Filesystem usrmerge must not be done in singletrans mode

zypp/ZConfig.cc, zypp/ZConfig.h, zypp/repo/RepoVariables.cc
[bsc#1237044](https://bugzilla.suse.com/show_bug.cgi?id=1237044)
openSUSE/zypper#599
=> Fix context of repo variable evaluation

zypp/media/MediaCurl.cc
[bsc#1244105](https://bugzilla.suse.com/show_bug.cgi?id=1244105)
=> Fix credential handling in HEAD requests

zypp/target/RpmPostTransCollector.cc, zypp/target/RpmPostTransCollector.h, zypp/target/TargetImpl.cc
[bsc#1243279](https://bugzilla.suse.com/show_bug.cgi?id=1243279)
=> Pass $1==2 to %posttrans script if it's an update (bsc#1243279)

zypp/media/MediaDISK.cc
=> Fix SEGV in MediaDISK handler

zypp-core/MirroredOrigin.cc, zypp-core/MirroredOrigin.h, zypp/RepoManager.cc, zypp/repo/PackageDelta.cc, zypp/repo/PackageProvider.cc, zypp/repo/RepoProvideFile.cc
[bsc#1245672](https://bugzilla.suse.com/show_bug.cgi?id=1245672)
=> Unavailable delta rpms cause a user report rather than being ignored

zypp/target/rpm/RpmDb.cc
[bsc#1246149](https://bugzilla.suse.com/show_bug.cgi?id=1246149)
=> Add runtime check for a broken rpm-4.18 --runpostrans

zypp-curl/proxyinfo/proxyinfolibproxy.cc
[bsc#1247690](https://bugzilla.suse.com/show_bug.cgi?id=1247690)
=> Fix evaluation of libproxy results (bsc#1247690)

zypp-logic/zypp-core/fs/TmpPath.cc, zypp-logic/zypp-core/fs/TmpPath.h
[bsc#1249435](https://bugzilla.suse.com/show_bug.cgi?id=1249435)
=> Ease proper se linux labelling
